In [1]:
#Importing necessary Libraries
import numpy as np
import pandas as pd

# load and evaluate a saved model
from numpy import loadtxt
from tensorflow.keras.models import load_model
 
# load model
model = load_model('/UCordoba/Machine Learning/ANN.h5')
# summarize model.
model.summary()
"""
# load dataset
dataset = loadtxt("pima-indians-diabetes.csv", delimiter=",")
# split into input (X) and output (Y) variables
X = dataset[:,0:8]
Y = dataset[:,8]
# evaluate the model
score = model.evaluate(X, Y, verbose=0)
print("%s: %.2f%%" % (model.metrics_names[1], score[1]*100))"""

WARNING:tensorflow:From C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_24 (Dense)            (None, 6)                 72

 dense_25 (Dense)            (None, 1)                 7

=================================================================
Total params: 79 (316.00 Byte)
Trainable params: 79 (316.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

'\n# load dataset\ndataset = loadtxt("pima-indians-diabetes.csv", delimiter=",")\n# split into input (X) and output (Y) variables\nX = dataset[:,0:8]\nY = dataset[:,8]\n# evaluate the model\nscore = model.evaluate(X, Y, verbose=0)\nprint("%s: %.2f%%" % (model.metrics_names[1], score[1]*100))'

In [6]:

#se define un data frame para cargar el archivo que contiene los datos de entrenamiento
#temp = pd.read_csv("/UCordoba/Machine Learning/Data/Sickle_data2.csv")
temp = pd.read_csv("/UCordoba/Machine Learning/Data/Sickle_data.csv")
#se muestra el dataframe
temp

,Age,Sex,RBC,PCV,MCV,MCH,MCHC,RDW,TLC,PLT /mm3,HGB,Target
0,28,0,5.66,34.0,60.1,17.0,28.2,20.0,11.10,128.3,9.6,0
1,41,0,4.78,44.5,93.1,28.9,31.0,13.0,7.02,419.0,13.8,0
2,40,1,4.65,41.6,89.5,28.8,32.2,13.0,8.09,325.0,13.4,0
3,76,0,4.24,36.7,86.6,26.7,30.8,14.9,13.41,264.0,11.3,0
4,20,1,4.14,36.9,89.1,27.8,31.2,13.2,4.75,196.0,11.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...
359,17,0,4.86,39.2,80.7,27.7,34.4,13.4,4.40,180.0,13.5,0
360,51,0,4.85,35.2,91.7,31.0,33.8,13.3,5.60,215.0,15.0,0
361,21,1,4.47,39.7,88.7,29.3,33.0,13.5,9.20,329.0,13.1,0
362,35,1,4.75,36.2,86.7,27.9,32.1,13.5,6.48,174.0,13.2,0
363,26,0,4.95,44.4,89.7,30.6,34.2,12.3,8.80,279.0,15.2,0

In [9]:
#Se elimina los espacios al principio y al final de la cadena:
#en el eventual caso de que los hubiera
temp.columns=temp.columns.str.strip()

In [10]:
#En X se separan las variables independientes, en este caso el tamo de los granos de arena
#X= dfNetwork[['src_port','dst_port','bidirectional_first_seen_ms','bidirectional_last_seen_ms','bidirectional_bytes']]
X= temp[['Age','Sex','RBC','MCV','PCV','MCH','MCHC','RDW','TLC','PLT /mm3','HGB']]

X                 
#En y se asigna la variable dependiente que en este caso presencia de araÃ±as (donde 1 indicia que hay araÃ±as y 0 no hay araÃ±as)
y=temp['Target']
#Se visualizan las variables independientes 
X.head()

   Age  Sex   RBC   MCV   PCV   MCH  MCHC   RDW    TLC  PLT /mm3   HGB
0   28    0  5.66  60.1  34.0  17.0  28.2  20.0  11.10     128.3   9.6
1   41    0  4.78  93.1  44.5  28.9  31.0  13.0   7.02     419.0  13.8
2   40    1  4.65  89.5  41.6  28.8  32.2  13.0   8.09     325.0  13.4
3   76    0  4.24  86.6  36.7  26.7  30.8  14.9  13.41     264.0  11.3
4   20    1  4.14  89.1  36.9  27.8  31.2  13.2   4.75     196.0  11.5

In [11]:

#train_test_split permite la separaciÃ³n de datos de entrenamiento y pruebas
from sklearn.model_selection import train_test_split
#Se dividen los datos en en entrenamiento y pruebas, ademÃ¡s se define mediante test_size=0.2 el porcentaje para pruebas
#TambiÃ©n se puede definir de forma aleatoria que datos se utilizarÃ¡n para el entrenamiento mediante random_state=10
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.3, random_state=30)

In [13]:
score = model.evaluate(X_test, y_test, verbose=0)
print("%s: %.2f%%" % (model.metrics_names[1], score[1]*100))

WARNING:tensorflow:From C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

accuracy: 87.27%

In [17]:
print (model.predict([[25,	1,	3.04,	30.1,	99,	29.9,	30.2,	17.4,	4.64,	241,	9.1]]))

1/1 [==============================] - 0s 51ms/step
[[0.]]